import { Class } from "../types";

const mockClasses: Omit<Class, "issues">[] = [
  {
    id: "1",
    name: "Turma A",
    segment: "Ensino Médio",
    year: "1ª Série",
    type: "Regular",
    teacherCount: 7,
    studentCount: 26,
    isNew: true,
  },
  {
    id: "2",
    name: "Turma B",
    segment: "Ensino Médio",
    year: "1ª Série",
    type: "a",
    teacherCount: 7,
    studentCount: 26,
    isNew: true,
  },
  {
    id: "3",
    name: "Turma C",
    segment: "Ensino Médio",
    year: "1ª Série",
    type: "",
    teacherCount: 7,
    studentCount: 26,
    isNew: false,
  },
  {
    id: "4",
    name: "Turma D",
    segment: "Ensino Médio",
    year: "1ª Série",
    type: "Trilha",
    teacherCount: 7,
    studentCount: 26,
    isNew: true,
  },
  {
    id: "5",
    name: "Turma E",
    segment: "Ensino Médio",
    year: "2ª Série",
    type: "Mista",
    teacherCount: 6,
    studentCount: 24,
    isNew: true,
  },
  {
    id: "6",
    name: "Turma F",
    segment: "Ensino Médio",
    year: "2ª Série",
    type: "Regular",
    teacherCount: 5,
    studentCount: 22,
    isNew: false,
  },
  {
    id: "7",
    name: "Turma G",
    segment: "Ensino Médio",
    year: "3ª Série",
    type: "Trilha",
    teacherCount: 8,
    studentCount: 28,
    isNew: true,
  },
  {
    id: "8",
    name: "Turma H",
    segment: "Ensino Médio",
    year: "3ª Série",
    type: "Regular",
    teacherCount: 7,
    studentCount: 25,
    isNew: false,
  },
  {
    id: "9",
    name: "Turma I",
    segment: "Ensino Médio",
    year: "1ª Série",
    type: "Regular",
    teacherCount: 5,
    studentCount: 20,
    isNew: true,
  },
  {
    id: "10",
    name: "Turma J",
    segment: "Ensino Médio",
    year: "1ª Série",
    type: "Mista",
    teacherCount: 6,
    studentCount: 23,
    isNew: false,
  },

  {
    id: "11",
    name: "&Åbcdef 78/",
    segment: "Ensino Médio",
    year: "1ª Série",
    type: "Regular",
    teacherCount: 7,
    studentCount: 26,
    isNew: true,
  },
  {
    id: "12",
    name: "Turma L",
    segment: "Ensino Médio",
    year: "1ª Série",
    type: null,
    teacherCount: 7,
    studentCount: 26,
    isNew: false,
  },
  {
    id: "13",
    name: "Turma M",
    segment: "Ensino Médio",
    year: "2ª Série",
    type: "Regular",
    teacherCount: 0,
    studentCount: 26,
    isNew: true,
  },
  {
    id: "14",
    name: "Turma N",
    segment: "Ensino Médio",
    year: "1ª Série",
    type: "Mista",
    teacherCount: 7,
    studentCount: 26,
    isNew: true,
  },
];

export function getMockClasses(): Omit<Class, "issues">[] {
  return [...mockClasses];
}
